services:
    kavita:
        image: jvmilazz0/kavita:latest
        container_name: kavita
        volumes:
            - /srv/media/manga:/manga
            - /srv/media/comics:/comics
            - /srv/media/books:/books
            - /srv/kavita/config:/kavita/config
        environment:
            - TZ=Etc/UTC
        ports:
            - "5000:5000"
        restart: unless-stopped

